version: '3.1'
services:
  mysql:
      hostname: "localhost"
      network_mode: "bridge"
      command: 
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8 
        --collation-server=utf8_unicode_ci
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_USER=root
        - MYSQL_PASS=123456
        - TZ=Asia/Shanghai
      image: "mysql"
      container_name: "mysql_1"
      restart: always
      volumes:
        - "./db:/var/lib/mysql"
        - "./conf/my.cnf:/etc/my.cnf"
        - "./init:/docker-entrypoint-initdb.d/"
      ports:
        - "3306:3306"
