version: '3.7'

services:
  redis:
    image: redis:5.0
    container_name: redis
    network_mode: bridge
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command:
      redis-server /etc/redis/redis.conf